/*
  Warnings:

  - The values [PENDING,DEPLOYING] on the enum `DEPLOYMENT_STATUS` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "DEPLOYMENT_STATUS_new" AS ENUM ('READY', 'IN_PROGRESS', 'IDLE', 'SUCCESS', 'FAILED', 'CANCELLED', 'QUEUED');
ALTER TABLE "Deployment" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Deployment" ALTER COLUMN "status" TYPE "DEPLOYMENT_STATUS_new" USING ("status"::text::"DEPLOYMENT_STATUS_new");
ALTER TYPE "DEPLOYMENT_STATUS" RENAME TO "DEPLOYMENT_STATUS_old";
ALTER TYPE "DEPLOYMENT_STATUS_new" RENAME TO "DEPLOYMENT_STATUS";
DROP TYPE "DEPLOYMENT_STATUS_old";
ALTER TABLE "Deployment" ALTER COLUMN "status" SET DEFAULT 'IDLE';
COMMIT;

-- AlterTable
ALTER TABLE "Deployment" ALTER COLUMN "status" SET DEFAULT 'IDLE';
